
//
//  APIConstant.swift
//  SaveMe
//
//  Created by Vengile on 26/04/2017.
//  Copyright © 2017 Vengile. All rights reserved.
//

import Foundation

let kSessionKey = ""
//http://139.162.37.73/healingbudz_live
//http://138.68.229.113/healingbudz/
//https://healingbudz.cannablazeed.com/

enum WebServiceName: String {
    //save_share
    case GoogleImage_BaseURL                         = "https://maps.google.com/maps/api/staticmap?center="
    case GoogleImage_EndURL                         = "&zoom=19&size=1080x200&sensor=false"
    
//    case images_baseurl               = "http://139.162.37.73/healingbudz_live/public/images"
//    case videos_baseurl                         = "http://139.162.37.73/healingbudz_live/public/videos"
//    case shareUrl                               = "http://139.162.37.73/healingbudz_live/get-post/"

    case images_baseurl               = "https://healingbudz.com/public/images"
    case videos_baseurl                         = "https://healingbudz.com/public/videos"
    case shareUrl                               = "https://healingbudz.com/get-post/"
    case save_share                             = "save_share"
    case logout                                 = "logout"
    case check_email_availablity                = "check_email"
    case delete_subscription                    = "delete_subscription/"
    case get_defaults                           = "get_defaults"
    case register                               = "register"
    case login                                  = "login"
    case social_login                           = "social_login"
    case refresh_user_data                      = "get_user_session"
    case globle_search                          = "globle_search"
    case upload_profile_img                     = "add_image_profile"
    case upload_strain_image                    = "upload_strain_image"
    case get_expertise                          = "get_expertise"
    case add_expertise                          = "add_expertise"
    case add_question                           = "add_question"
    case get_activities                         = "get_activities/"
    case filter_activity                        = "filter_activity/"
    case get_questions                          = "get_questions?sort="
    case get_question                           = "get_question/"
    case get_answer_question                    = "get_answer_question"
    case get_answers                            = "get_answers/"
    case get_answer                             = "get_answer"
    case add_answer                             = "add_answer"
    case add_image                              = "add_image"
    case update_image                           = "update_image"
    case update_cover                           = "update_cover"
     case update_cover_orignal_image            = "update_cover_orignal_image"
    case add_video                              = "add_video"
    case update_avatar                          = "update_avatar"
    case add_question_like                      = "add_question_like"
    case add_question_flag                      = "add_question_flag"
    case search_question                        = "search_question?query="
    case add_answer_like                        = "add_answer_like"
    case update_special_icon                    = "update_special_icon"
    case add_answer_flag                        = "add_answer_flag"
    case get_user_profile                       = "get_user_profile/"
    case update_bio                             = "update_bio"
    case update_email                           = "update_email"
    case change_password                        = "change_password"
    case update_zip                             = "update_zip"
    case update_name                            = "update_name"
    case follow_user                            = "follow_user"
    case un_follow                              = "un_follow"
    case get_chats                              = "get_chats"
    case get_budz_chats                         = "get_budz_chats"
    case get_detail_chat                        = "get_detail_chat"
    case get_users                              = "get_users"
    case send_message                           =  "send_message"
    case add_group_message                      = "add_group_message"
    case add_image_chat                         = "add_image_chat"
    case add_video_chat                         = "add_video_chat"
    case search_users                           = "search_users?query="
    case get_groups                             = "get_groups"
    case get_all_public_groups                  = "get_all_public_groups"
    case get_group_messgaes                     = "get_messgaes"
    case add_message_like                       = "add_message_like"
    case remove_message_like                    = "remove_message_like"
    case add_group                              = "add_group"
    case get_tags                               = "get_tags"
    case get_all_public_groups_alpha            =   "get_all_public_groups_alpha"
    case get_all_public_groups_created          = "get_all_public_groups_created"
    case get_all_gublic_groups_joined           = "get_all_gublic_groups_joined"
    case search_group                           = "search_group"
    case join_group                             = "join_group"
    case delete_chat                            = "delete_chat"
    case invite_members                         = "invite_members"
    case remove_member                          = "remove_member"
    case accept_reject_invitaion                = "accept_reject_invitaion"
    case remove_group                           = "remove_group"
    case leave_group                            = "leave_group"
    case get_user_groups                        = "get_user_groups"
    case get_my_question                        = "get_my_question?page_no="
    case get_my_answers                         = "get_my_answers?page_no="
    case edit_group                             = "edit_group"
    case get_my_groups                          = "get_my_groups?page_no="
    case get_user_profile_strains               = "get_user_profile_strains/"
    case create_journal                         = "create_journal"
    case add_subscription                       = "add_subscription"
    case update_journal                         = "update_journal"
    case delete_journal                         = "delete_journal"
    case get_user_all_journals                  = "get_user_all_journals"
    case get_my_journals_sorting                = "get_my_journals_sorting"
    case get_journal_tags                       = "get_journal_tags"
    case strain_details_by_name                 = "strain_details_by_name"
    case get_all_journals                       = "get_all_journals"
    case search_journal                         = "search_journal"
    case get_journal_events                     = "get_journal_events"
    case delete_journal_event                   = "delete_journal_event"
    case follow_journal                         = "follow_journal"
    case favourtire_journal                     = "favourtire_journal"
    case strain_flaged                          = "strain_flaged"
    case check_special_email                    = "check_special_email"
    case save_favorit_strain                    = "save_favorit_strain"
    case add_group_settings                     = "add_group_settings"
    case group_settings                         = "group_settings"
    case hb_gallery                             = "hb_gallery/"
    case add_event_image                        = "add_event_image"
    case add_event_video                        = "add_event_video"
    case create_journal_event                   = "create_journal_event"
    case journal_like_or_dislike                = "journal_like_or_dislike"
    case strain_like_dislike                    = "strain_like_dislike"
    case get_strains                            = "get_strains"
    case get_strain                             = "get_strain"
    case get_budz                               = "get_budz/"
    case get_strains_alphabitically             = "get_strains_alphabitically"
    case get_strains_by_type                    = "get_strains_by_type"
    case add_strain_review                      = "add_strain_review"
    case get_strain_detail                      = "get_strain_detail/"
    case flag_strain_review                     = "flag_strain_review"
    case save_user_strain                       = "save_user_strain"
    case save_strain_search                     = "save_strain_search"
    case get_user_strain                        = "get_user_strains/"
    case search_strain_name                     = "search_strain_name?name="
    case save_user_strain_like                  = "save_user_strain_like"
    case locate_strain_budz                     = "locate_strain_budz?strain_id="
    case save_survey_answer                     = "save_survey_answer"
    case search_strain_survey                   = "search_strain_survey?"
    case delete_question                        = "delete_question/"
    case delete_answer                          = "delete_answer/"
    case add_shout_out                          = "add_shout_out"
    case get_shout_outs                         = "user_shout_outs"
    case get_notifications                      = "get_notifications"
    case filter_my_save                         = "filter_my_save?filter="
    case delete_my_save                         = "delete_my_save"
    case get_my_save                            = "get_my_save"
    case delete_budz_review                     = "delete_budz_review"
    case get_my_strains                         = "get_my_strains?page_no="
    case delete_sub_user                         = "delete_sub_user"
    case delete_user_strain                     = "delete_user_strain"
    case get_my_journals_calander               = "get_my_journals_calander"
    case add_journal_reminder_setting           = "add_journal_reminder_setting"
    case get_journal_settings                   = "get_journal_settings"
    case get_budz_map                           = "get_budz_map?"
    case my_get_budz_map                        = "my_budz_map"
    case my_feature_budz_map                        = "my_feature_budz_map"
    case user_my_get_budz_map                   = "get_user_profile_budz_map"
    case user_my_get_reviews                    = "get_user_profile_reviews"
    case add_listing                            = "add_listing"
    case add_logo                               = "add_logo"
    case add_banner                             = "add_banner"
    case save_favorit_bud                       = "save_favorit_bud"
    case get_languages                          = "get_languages"
    case get_budz_profile                       = "get_budz_profile/"
    case add_budz_review                        = "add_budz_review"
    case add_budz_image                         = "add_budz_image"
    case add_budz_review_flag                   = "add_budz_review_flag"
    case add_budz_flag                          = "add_budz_flag"
    case get_all_questions                      = "get_all_questions"
    case get_group                              = "get_group"
    case get_journal                            = "get_journal"
    case delete_user_post                       = "delete_post"
    case delete_comment                         = "delete_comment"
    case add_post_image                         = "add_post_image"
    case add_post_video                         = "add_post_video"
    case get_sub_users                          = "get_sub_users"
    case save_post                              = "save_post"
    case add_budz_review_reply                  = "add_budz_review_reply"
    case get_notification_settings              = "get_notification_settings"
    case remove_tag                             = "remove_tag"
    case add_notificarion_setting               = "add_notificarion_setting"
    case follow_keyword                         = "follow_keyword"
    case add_journal_setting                    = "add_journal_setting"
    case add_journal_data_setting               = "add_journal_data_setting"
    case get_user_strain_detail                 = "get_user_strain_detail"
    case get_followings                         = "get_followings/"
    case get_followers                          = "get_followers/"
    case delete_strain_review                   = "delete_strain_review"
    case delete_budz_review_reply               = "delete_budz_review_reply"
    case save_budz_call_click                   = "save_budz_call_click"
    case save_budz_menu_click                   = "save_budz_menu_click"
    case save_budzmap_share                     = "save_budzmap_share"
    case save_budz_ticket_click                 = "save_budz_ticket_click"
    case like_shout_out                         = "like_shout_out"
    case save_user_image_strain_like            = "save_user_image_strain_like"
    case save_user_image_strain_dislike            = "save_user_image_strain_dislike"
    case save_user_image_strain_flag            = "save_user_image_strain_flag"
    case suggest_medical_condition              = "suggest_medical_condition"
    case suggest_sensation              = "suggest_sensation"
    case suggest_negative_effect              = "suggest_negative_effect"
    case suggest_disease_prevention              = "suggest_disease_prevention"
    case update_pop_up                           = "update_pop_up"
    case update_subscription                    = "update_subscription"
    case getKeywords              = "get_keywords"
    case get_my_rewards =    "get_my_rewards"
     case get_user_point_log =    "get_user_point_log"
    case get_products = "get_products"
    case purchase_product = "purchase_product"
    case forget_password = "forget_password"
    case get_post   = "get_post"
    case mail_support = "mail_support"
    case add_comment_like_dislike = "add_comment_like_dislike"
    case user_posts             = "user_posts"
    case get_user_posts = "get_user_posts"
    case add_post_like_dislike = "add_post_like_dislike"
    case add_comment           = "add_comment"
    case repost                = "repost"
    case mute_post             = "mute_post"
    case add_post_flag         = "add_post_flag"
    //case un_follow             = "un_follow"
    case user_post_comment      = "user_post_comment"
    case update_password        = "update_password"
    case invite = "invite"
}


var kBaseURLString: String {

    return "https://healingbudz.com/api/v1/"
//    return "https://healingbudz.cannablazeed.com/api/v1/"

//       return "http://139.162.37.73/healingbudz/api/v1/"
//       return "http://139.162.37.73/healingbudz_live/api/v1/"
//     return "http://healingbudz.codingpixel.co/api/v1/"
}
